# Generated by Django 5.0.6 on 2024-08-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
