# Generated by Django 5.0.6 on 2024-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoruser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(upload_to='authoruser/images/'),
        ),
    ]
