# Generated by Django 5.0.6 on 2024-07-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoruser', '0002_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
